version: '3'

services:
  taskmanager-db:
    image: postgres
    container_name: taskmanager_db
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_DB: taskmanager
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/db-files/
    # volumes:
    #   - db-data:/var/lib/postgresql/data
  pgadmin:
    container_name: taskmanager_pgadmin
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - taskmanager-db
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: madbazsa@gmail.com
      PGADMIN_DEFAULT_PASSWORD: madbazsa

  taskmanager-redis:
    image: redis:alpine
    container_name: taskmanager_redis

  taskmanager-server:
    container_name: taskmanager_server
    build:
      dockerfile: Dockerfile-dev
      context: .
    ports:
      - '3000:3000'
    command: yarn start:dev
    volumes:
      - './src:/home/node/app/src'
    environment:
      - REDIS_HOST=taskmanager-redis

    depends_on:
      - taskmanager-db
      - taskmanager-redis

volumes:
  db-data:
